services:
  enclave-batch-poster:
    image: # ghcr.io/espressosystems/aws-nitro-poster:<docker-tag>
    devices:
      - "/dev/nitro_enclaves:/dev/nitro_enclaves:rwm"
    ports:
      - "8547:8547"
      - "8548:8548"
    privileged: true